export default {
  'authentication': '&#xe657;', // 实名认证-认证中
  'success': '&#xe656;', // 实名认证-成功
  'add': '&#xe655;', // 添加
  'open': '&#xe654;', // 展开
  'time': '&#xe653;', // 时间
  'distance': '&#xe652;', // 距离
  'level': '&#xe651;', // 等级
  'replace': '&#xe650;', // 更换
  'edit': '&#xe64f;', // 编辑
  'telephone': '&#xe64e;', // 电话
  'up': '&#xe64d;', // 箭头-上
  'down': '&#xe64c;', // 箭头-下
  'left': '&#xe64b;', // 箭头-左
  'right': '&#xe64a;', // 箭头-右
  'tip': '&#xe649;', // 提示
  'close': '&#xe648;', // 关闭
  'hospital': '&#xe647;', // 医院
  'delete': '&#xe646;', // 删除
  'search': '&#xe645;', // 搜索
  'clear': '&#xe644;', // 清除
  'selected': '&#xe643;', // 选中
  'select': '&#xe642;', // 未选择
  'more': '&#xe641;', // 更多
  'weChat': '&#xe640;', // 微信C
  'phone': '&#xe63f;', // 手机号
  'collect': '&#xe63e;', // 收藏
  'ghCancel': '&#xe63d;', // 挂号取消
  'ghSuccess': '&#xe63c;' // 挂号成功
}
